### PR TITLE
Support of Bandwidth and Storage metrics

### PR DESCRIPTION
**Pull request by jpedro1992**
#### What type of PR is this?

Addition of bandwidth and storage metrics in load-watcher.

#### Related issue

#58

#### Summary

Additional metrics:

```
promTransBandMetric     = "instance:node_network_transmit_bytes:rate:sum"
promTransBandDropMetric = "instance:node_network_transmit_drop_excluding_lo:rate5m"
promRecBandMetric       = "instance:node_network_receive_bytes:rate:sum"
promRecBandDropMetric   = "instance:node_network_receive_drop_excluding_lo:rate5m"
promDiskIOMetric        = "instance_device:node_disk_io_time_seconds:rate5m"
```

### CODE REVIEW

**Comment by jpedro1992** [comment]
I can remove the vendor dependencies by doing a reset if you prefer. What do you think?

**Comment by lenhattan86** [comment]
is it still compiled (generated) without the vendor? If so, please go ahead.

**Comment by jpedro1992** [comment]
Well, I need to run `go mod vendor` to be able to run a few tests (e.g., `watcher_test.go`).

Several dependencies needed an update.

**Comment by lenhattan86** [comment]
which go version are you using? 
I think we can skip vendor as anyone can generate it for building and testing.

**Comment by jpedro1992** [comment]
> which go version are you using? I think we can skip vendor as anyone can generate it for building and testing.

I am using go 1.16. I just removed the vendor dependencies from the PR and I squashed both commits into a single one.

**Review by lenhattan86 — APPROVED** [review]
looks good to me.

**Comment by lenhattan86** [comment]
@wangchen615  can you approve this PR, it needs your approval.

**Review by wangchen615 — APPROVED** [review]
Thanks so much, @jpedro1992 , the commits look good to me.

/lgtm

**Pull request merged**
